### ISSUE TITLE
Hyperparameters for artistic style transfer

### ISSUE THREAD

**Issue by theJulman** [EndyWon/GLStyleNet#2]
I quite like the results of this approach, but i couldn`t get the same results in the artistic style transfer as you. Which Hyperparameters were used to generate the artistic style images?

**Comment by EndyWon** [comment]
For artistic style images without semantic maps, the semantic weight should be set to 0, and global weight should not be set too high, 0.001-1 is suitable, local weight can be set to 10-100.

**Comment by theJulman** [comment]
Ok, thank you very much.
