### ISSUE TITLE
photo-realistic

### ISSUE THREAD

**Issue by happyhugo** [EndyWon/GLStyleNet#3]
please tell me about photo-realistic's parameter

**Comment by EndyWon** [comment]
Hi, for photo-realistic style transfer, try and fine-tune local-weight=20, semantic-weight=10 and global-weight=0.001. In our latest version, the results will be followed by a bilateral filter to get more photo-realistic effect. We will update soon.

**Comment by happyhugo** [comment]
ok.thank you,i will try this parameters

**Comment by destiny-xb** [comment]
can you tell me artistic‘s parameter，thanks

**Comment by EndyWon** [comment]
try and fine-tune local-weight=10, semantic-weight=0 and global-weight=0.01
