### ISSUE TITLE
Optimizer

### ISSUE THREAD

**Issue by happyhugo** [EndyWon/GLStyleNet#5]
hi, I want to chang the code to fast model. so i want change optimizer to tf.contrib.opt.ScipyOptimizerInterface(self.loss, method='L-BFGS-B') ,but I found the effect is not good as yours. Do you have any idea? and in evaluate function, why minus self.pixel_mean everytime?

**Comment by EndyWon** [comment]
The fast optimizer('L-BFGS-B') may converge to a not so good optimal point. For evaluation function, subtracting self.pixel_mean is to center the data.

**Comment by JanBoskamp** [comment]
@happyhugo, did you manage to create a fast model? If so, can you share your code? Thanks!
