### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by jeffrefuu** [EndyWon/GLStyleNet#6]
i just tried to run the code ,but it reported me an error that i cannot deal it.
can you tell me how to do
![21f9cd224a5b2b2d9dba5a5e38f89b3](https://user-images.githubusercontent.com/100703316/156190810-c976eec8-f6a9-4e72-b6b2-2c7b85f01b36.jpg)

**Comment by EndyWon** [comment]
What's the version of your TensorFlow? Try to run the code on TF 1.4.0 (pip install tensorflow-gpu==1.4.0).

**Comment by jeffrefuu** [comment]
the version of Tensorflow is  2.7.0 and  "CUDA“ is 11.1

**Comment by jeffrefuu** [comment]
> What's the version of your TensorFlow? Try to run the code on TF 1.4.0 (pip install tensorflow-gpu==1.4.0).

hello author, i just tried to use quote your code to do sth, but the enviroment  version is too old to i cannot use the machine to do this , and i think that this code can update the enviroment requirement?, and what i need to do?
hope your reaction,thx

**Comment by EndyWon** [comment]
You may need to update the syntax of the code to support TF2.0. 

This link may be helpful: https://blog.csdn.net/donruo/article/details/118681094

Good luck!

**Comment by jeffrefuu** [comment]
> You may need to update the syntax of the code to support TF2.0.
> 
> This link may be helpful: https://blog.csdn.net/donruo/article/details/118681094
> 
> Good luck!

感谢大佬，
本人还有一个问题：当我根据reuqirement建立环境后运行该代码，我的机器能够跑出您给的example的图片，但是当我运用该代码跑自己的图片时，就出现图片中的报错，请问是我的图片问题吗？图片的格式应该如何正确处理才能完美运行该代码，请大佬教一下萌新，非常感谢
![QQ图片20220308201659](https://user-images.githubusercontent.com/100703316/157236890-eb103467-ef8b-401c-9127-1ed7d9788166.jpg)

**Comment by EndyWon** [comment]
请问你的语义图是jpg格式还是png格式（png格式多一个alpha通道）？你拍的照片报的错似乎是Kmeans聚类那块出了问题，可以尝试调整一下--class_num的值，或者直接注释掉这部分的代码，对结果的影响应该不会特别大。
